name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install --frozen-lockfile
    - run: yarn run build
  check:
    name: Lint and Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install --frozen-lockfile
    - run: yarn run check
    - run: yarn run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install --frozen-lockfile
    - run: yarn run coverage
    - run: yarn run codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
